#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v20
# autospec commit: f35655a
#
Name     : libnvme
Version  : 1.11
Release  : 12
URL      : https://github.com/linux-nvme/libnvme/archive/v1.11/libnvme-1.11.tar.gz
Source0  : https://github.com/linux-nvme/libnvme/archive/v1.11/libnvme-1.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 LGPL-2.1 MIT
Requires: libnvme-lib = %{version}-%{release}
Requires: libnvme-license = %{version}-%{release}
Requires: libnvme-python = %{version}-%{release}
Requires: libnvme-python3 = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : openssl-dev
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libkeyutils)
BuildRequires : python3-dev
BuildRequires : swig
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libnvme
![MesonBuild](https://github.com/linux-nvme/libnvme/actions/workflows/build.yml/badge.svg)
![PyBuild](https://github.com/linux-nvme/libnvme/actions/workflows/release-python.yml/badge.svg)
[![PyPI](https://img.shields.io/pypi/v/libnvme)](https://pypi.org/project/libnvme/)
[![PyPI - Wheel](https://img.shields.io/pypi/wheel/libnvme)](https://pypi.org/project/libnvme/)
![GitHub](https://img.shields.io/github/license/linux-nvme/libnvme)
[![codecov](https://codecov.io/gh/linux-nvme/libnvme/branch/master/graph/badge.svg)](https://codecov.io/gh/linux-nvme/libnvme)
[![Read the Docs](https://img.shields.io/readthedocs/libnvme)](https://libnvme.readthedocs.io/en/latest/)

%package dev
Summary: dev components for the libnvme package.
Group: Development
Requires: libnvme-lib = %{version}-%{release}
Provides: libnvme-devel = %{version}-%{release}
Requires: libnvme = %{version}-%{release}

%description dev
dev components for the libnvme package.


%package lib
Summary: lib components for the libnvme package.
Group: Libraries
Requires: libnvme-license = %{version}-%{release}

%description lib
lib components for the libnvme package.


%package license
Summary: license components for the libnvme package.
Group: Default

%description license
license components for the libnvme package.


%package python
Summary: python components for the libnvme package.
Group: Default
Requires: libnvme-python3 = %{version}-%{release}

%description python
python components for the libnvme package.


%package python3
Summary: python3 components for the libnvme package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libnvme package.


%prep
%setup -q -n libnvme-1.11
cd %{_builddir}/libnvme-1.11
pushd ..
cp -a libnvme-1.11 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1730385424
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs
cd ../buildavx2;
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libnvme
cp %{_builddir}/libnvme-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libnvme/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/array_size/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/build_assert/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/check_type/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/container_of/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/endian/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/list/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/minmax/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/short_types/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/libnvme-%{version}/ccan/ccan/str/LICENSE %{buildroot}/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnvme-mi.h
/usr/include/libnvme.h
/usr/include/nvme/api-types.h
/usr/include/nvme/fabrics.h
/usr/include/nvme/filters.h
/usr/include/nvme/ioctl.h
/usr/include/nvme/linux.h
/usr/include/nvme/log.h
/usr/include/nvme/mi.h
/usr/include/nvme/nbft.h
/usr/include/nvme/tree.h
/usr/include/nvme/types.h
/usr/include/nvme/util.h
/usr/lib64/libnvme-mi.so
/usr/lib64/libnvme.so
/usr/lib64/pkgconfig/libnvme-mi.pc
/usr/lib64/pkgconfig/libnvme.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libnvme-mi.so.1.11.0
/V3/usr/lib64/libnvme.so.1.11.0
/usr/lib64/libnvme-mi.so.1
/usr/lib64/libnvme-mi.so.1.11.0
/usr/lib64/libnvme.so.1
/usr/lib64/libnvme.so.1.11.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libnvme/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libnvme/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305
/usr/share/package-licenses/libnvme/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
